# Generated by Django 3.0.2 on 2020-01-31 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_auto_20200130_2300'),
        ('vendas', '0002_remove_pedido_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='produto.Produto'),
            preserve_default=False,
        ),
    ]
