# Generated by Django 3.0.2 on 2020-01-31 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_auto_20200130_2300'),
        ('vendas', '0004_auto_20200131_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.Produto'),
        ),
    ]
