# Generated by Django 3.0.2 on 2020-02-01 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_auto_20200131_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7, verbose_name='Preço'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='quantidade',
            field=models.CharField(default=1, max_length=10, verbose_name='Quantidade'),
            preserve_default=False,
        ),
    ]
