# Generated by Django 3.0.2 on 2020-02-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_auto_20200131_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='quantidade',
            field=models.IntegerField(max_length=10, verbose_name='Quantidade'),
        ),
    ]
